#!/bin/bash

# --- Command line arguments ---

show_help() {
    cat <<EOF
Usage: ${0##*/} [OPTIONS]

Options:
  -d, --debug    Enable debug mode
  -c, --catchup  Late learner to test catchup
  -l, --loss     Packet loss rate
  -n, --num NUM  Number of values generated by each client (default: 1)
  -h, --help     Show this help message and exit
EOF
}

# Default values
MCAST_IP=239.1.2.3
DEBUG=false
NUM_VALUES=1
LOSS=0.0
CATCHUP=false
SLEEP=2

NUM_CLIENTS=1
NUM_PROPOSERS=1
NUM_ACCEPTORS=3
NUM_LEARNERS=2

# Parse options
POSITIONAL=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --ip)
            MCAST_IP="$2"
            shift 2
            ;;
        -d|--debug)
            DEBUG=true
            shift
            ;;
        -n|--num)
            NUM_VALUES="$2"
            shift 2
            ;;
        --loss)
            LOSS="$2"
            shift 2
            ;;
        --catchup)
            CATCHUP=true
            shift
            ;;
        -s|--sleep)
            SLEEP="$2"
            shift 2
            ;;
        -c|--clients)
            NUM_CLIENTS="$2"
            shift 2
            ;;
        -p|--proposers)
            NUM_PROPOSERS="$2"
            shift 2
            ;;
        -a|--acceptors)
            NUM_ACCEPTORS="$2"
            shift 2
            ;;
        -l|--learners)
            NUM_LEARNERS="$2"
            shift 2
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        -*)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
        *)
            POSITIONAL+=("$1")
            shift
            ;;
    esac
done

# Restore positional arguments
set -- "${POSITIONAL[@]}"

# Expect exactly 0 positional args
if [[ $# -ne 0 ]]; then
    echo "Error: no positional arguments expected"
    show_help
    exit 1
fi

# Debug output
if $DEBUG; then
    echo "[DEBUG] Debug mode enabled"
fi

# Packet loss
if [[ $LOSS != "0.0" ]]; then
  sudo iptables -A INPUT -d $MCAST_IP -m statistic --mode random --probability $LOSS -j DROP
fi

# --- Preparation ---

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$script_dir/../"

rm -rf logs
mkdir -p logs

pkill -f "python3 src/main.py"


# --- Generating config ---

jq -n --arg ip "$MCAST_IP" \
  '{clients: {ip: $ip, port: 5000},
    proposers: {ip: $ip, port: 6000},
    acceptors: {ip: $ip, port: 7000},
    learners: {ip: $ip, port: 8000}}' > logs/config.json

# --- Generating client values ---

for ((i = 1; i <= ${NUM_CLIENTS}; i++)); do
  if [[ $NUM_VALUES == "" ]]; then
    echo "Usage $0 <number of values>"
    exit
  fi

  for ((j = 0; j < $NUM_VALUES; j++)); do
    echo "$RANDOM" >> "logs/values$i.log"
  done
done

# --- Starting processes ---

postfix=""
if [[ $DEBUG == "true" ]]; then
  postfix=" --debug"
fi


echo "Starting acceptors..."
for ((i = 1; i <= ${NUM_ACCEPTORS}; i++)); do
  python3 src/main.py -r acceptor -p $i $postfix &> "logs/acceptor$i.log" &
done
sleep 1


echo "Starting learners..."
if ! $CATCHUP && [[ ${NUM_LEARNERS} > 0 ]]; then
  python3 src/main.py -r learner -p 1 $postfix &> "logs/learner1.log" &
fi
for ((i = 2; i <= ${NUM_LEARNERS}; i++)); do
  python3 src/main.py -r learner -p $i $postfix &> "logs/learner$i.log" &
done
sleep 1


echo "Starting proposers..."
for ((i = 1; i <= ${NUM_PROPOSERS}; i++)); do
  python3 src/main.py -r proposer -p $i $postfix &> "logs/proposer$i.log" &
done
sleep "$SLEEP"


echo "Starting clients..."
for ((i = 1; i <= ${NUM_CLIENTS}; i++)); do
  python3 src/main.py -r client -p $i $postfix < "logs/values$i.log" &> "logs/client$i.log" &
done
sleep "$SLEEP"

if $CATCHUP && [ "$NUM_LEARNERS" > 0 ]; then
  echo "Starting the late learner"
  python3 src/main.py -r learner -p 1 $postfix &> "logs/learner1.log" &
  sleep "$SLEEP"
fi

# --- Cleanup ---
echo "Killing everybody"
pkill -f "python3 src/main.py"
wait

# Reset packet loss
if [[ $LOSS != "0.0" ]]; then
  sudo iptables -S | grep $MCAST_IP | sed 's/^-A //' | while read rule; do
    sudo iptables -D $rule
  done
fi
